import {
  Layers,
  Scissors,
  Shrink,
  Image,
  ImagePlus,
  RotateCw,
  LockOpen,
  Lock,
  FileText,
  FileOutput,
  Sparkles,
  Languages,
  ScanText,
  SpellCheck,
  UserSearch,
  FileWarning,
  Receipt,
  MessageSquare,
  HelpCircle,
  FilePlus,
  ImageDown,
  PenLine,
  type LucideIcon,
} from "lucide-react";

export const iconRegistry: Record<string, LucideIcon> = {
  layers: Layers,
  scissors: Scissors,
  shrink: Shrink,
  image: Image,
  "image-plus": ImagePlus,
  "rotate-cw": RotateCw,
  "lock-open": LockOpen,
  lock: Lock,
  "file-text": FileText,
  "file-output": FileOutput,
  sparkles: Sparkles,
  languages: Languages,
  "scan-text": ScanText,
  "spell-check": SpellCheck,
  "user-search": UserSearch,
  "file-warning": FileWarning,
  receipt: Receipt,
  "message-square": MessageSquare,
  "help-circle": HelpCircle,
  "file-plus": FilePlus,
  "image-down": ImageDown,
  "pen-line": PenLine,
};

export function getIcon(name: string): LucideIcon {
  return iconRegistry[name] ?? FileText;
}
