import { ToolDefinition } from "@/lib/types/tool.types";

export const TOOLS: ToolDefinition[] = [
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    shortDescription: "Combine multiple PDFs into a single file, in the order you choose.",
    category: "pdf",
    inputType: "multi-file",
    acceptedFileTypes: ["pdf"],
    maxFiles: 20,
    requiresAiKey: false,
    endpoint: "/pdf/merge",
    icon: "layers",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    shortDescription: "Pull pages out of a PDF or break it into separate files.",
    category: "pdf",
    inputType: "single-file",
    acceptedFileTypes: ["pdf"],
    maxFiles: 1,
    requiresAiKey: false,
    endpoint: "/pdf/split",
    icon: "scissors",
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    shortDescription: "Shrink file size while keeping the document readable.",
    category: "pdf",
    inputType: "single-file",
    acceptedFileTypes: ["pdf"],
    maxFiles: 1,
    requiresAiKey: false,
    endpoint: "/pdf/compress",
    icon: "shrink",
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    shortDescription: "Turn each page of a PDF into a JPG image.",
    category: "pdf",
    inputType: "single-file",
    acceptedFileTypes: ["pdf"],
    maxFiles: 1,
    requiresAiKey: false,
    endpoint: "/pdf/to-jpg",
    icon: "image",
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    shortDescription: "Combine one or more images into a single PDF.",
    category: "pdf",
    inputType: "multi-file",
    acceptedFileTypes: ["image"],
    maxFiles: 20,
    requiresAiKey: false,
    endpoint: "/pdf/from-jpg",
    icon: "image-plus",
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    shortDescription: "Fix sideways or upside-down pages.",
    category: "pdf",
    inputType: "single-file",
    acceptedFileTypes: ["pdf"],
    maxFiles: 1,
    requiresAiKey: false,
    endpoint: "/pdf/rotate",
    icon: "rotate-cw",
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    shortDescription: "Remove a known password from a protected PDF.",
    category: "pdf",
    inputType: "single-file",
    acceptedFileTypes: ["pdf"],
    maxFiles: 1,
    requiresAiKey: false,
    requiresPassword: true,
    endpoint: "/pdf/unlock",
    icon: "lock-open",
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    shortDescription: "Add a password to keep a PDF private.",
    category: "pdf",
    inputType: "single-file",
    acceptedFileTypes: ["pdf"],
    maxFiles: 1,
    requiresAiKey: false,
    requiresPassword: true,
    endpoint: "/pdf/protect",
    icon: "lock",
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    shortDescription: "Convert a PDF into an editable Word document.",
    category: "pdf",
    inputType: "single-file",
    acceptedFileTypes: ["pdf"],
    maxFiles: 1,
    requiresAiKey: false,
    endpoint: "/pdf/to-word",
    icon: "file-text",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    shortDescription: "Convert a Word document into a PDF.",
    category: "pdf",
    inputType: "single-file",
    acceptedFileTypes: ["docx"],
    maxFiles: 1,
    requiresAiKey: false,
    endpoint: "/pdf/from-word",
    icon: "file-output",
  },
  {
    slug: "ai-pdf-summarizer",
    name: "AI PDF Summarizer",
    shortDescription: "Get a clear summary of a long PDF in seconds.",
    category: "ai",
    inputType: "single-file",
    acceptedFileTypes: ["pdf"],
    maxFiles: 1,
    requiresAiKey: true,
    endpoint: "/ai/summarize",
    icon: "sparkles",
  },
  {
    slug: "ai-document-translator",
    name: "AI Document Translator",
    shortDescription: "Translate a document into another language, formatting preserved.",
    category: "ai",
    inputType: "single-file",
    acceptedFileTypes: ["pdf", "docx"],
    maxFiles: 1,
    requiresAiKey: true,
    endpoint: "/ai/translate",
    icon: "languages",
  },
  {
    slug: "ai-ocr",
    name: "AI OCR",
    shortDescription: "Pull text out of scanned pages or photographed documents.",
    category: "ai",
    inputType: "single-file",
    acceptedFileTypes: ["pdf", "image"],
    maxFiles: 1,
    requiresAiKey: false,
    endpoint: "/ai/ocr",
    icon: "scan-text",
  },
  {
    slug: "ai-grammar-rewrite",
    name: "AI Grammar & Rewrite",
    shortDescription: "Clean up grammar and tighten the writing in a document.",
    category: "ai",
    inputType: "single-file",
    acceptedFileTypes: ["pdf", "docx"],
    maxFiles: 1,
    requiresAiKey: true,
    endpoint: "/ai/grammar",
    icon: "spell-check",
  },
  {
    slug: "ai-resume-analyzer",
    name: "AI Resume Analyzer",
    shortDescription: "Get feedback on a resume against a target role.",
    category: "ai",
    inputType: "single-file",
    acceptedFileTypes: ["pdf", "docx"],
    maxFiles: 1,
    requiresAiKey: true,
    endpoint: "/ai/resume-analyze",
    icon: "user-search",
  },
  {
    slug: "ai-contract-analyzer",
    name: "AI Contract Analyzer",
    shortDescription: "Flag risky clauses and get a plain-language breakdown.",
    category: "ai",
    inputType: "single-file",
    acceptedFileTypes: ["pdf", "docx"],
    maxFiles: 1,
    requiresAiKey: true,
    endpoint: "/ai/contract-analyze",
    icon: "file-warning",
  },
  {
    slug: "ai-invoice-extractor",
    name: "AI Invoice Data Extractor",
    shortDescription: "Turn an invoice into structured line-item data.",
    category: "ai",
    inputType: "single-file",
    acceptedFileTypes: ["pdf", "image"],
    maxFiles: 1,
    requiresAiKey: true,
    endpoint: "/ai/invoice-extract",
    icon: "receipt",
  },
  {
    slug: "ai-chat-with-pdf",
    name: "AI Chat with PDF",
    shortDescription: "Have a conversation about the contents of a document.",
    category: "ai",
    inputType: "single-file",
    acceptedFileTypes: ["pdf"],
    maxFiles: 1,
    requiresAiKey: true,
    endpoint: "/ai/chat",
    icon: "message-square",
  },
  {
    slug: "ai-pdf-qa",
    name: "AI PDF Q&A",
    shortDescription: "Ask direct questions and get answers sourced from the PDF.",
    category: "ai",
    inputType: "single-file",
    acceptedFileTypes: ["pdf"],
    maxFiles: 1,
    requiresAiKey: true,
    endpoint: "/ai/qa",
    icon: "help-circle",
  },
  {
    slug: "ai-document-generator",
    name: "AI Document Generator",
    shortDescription: "Generate a document from a short description.",
    category: "ai",
    inputType: "text-prompt",
    acceptedFileTypes: [],
    maxFiles: 0,
    requiresAiKey: true,
    endpoint: "/ai/generate-document",
    icon: "file-plus",
  },
  {
    slug: "ai-image-to-text",
    name: "AI Image to Text",
    shortDescription: "Extract any text found inside an image.",
    category: "ai",
    inputType: "single-file",
    acceptedFileTypes: ["image"],
    maxFiles: 1,
    requiresAiKey: false,
    endpoint: "/ai/image-to-text",
    icon: "image-down",
  },
  {
    slug: "ai-text-to-image",
    name: "AI Text to Image",
    shortDescription: "Generate an image from a written description.",
    category: "ai",
    inputType: "text-prompt",
    acceptedFileTypes: [],
    maxFiles: 0,
    requiresAiKey: true,
    endpoint: "/ai/text-to-image",
    icon: "image-plus",
  },
  {
    slug: "ai-proposal-writer",
    name: "AI Proposal Writer",
    shortDescription: "Draft a client proposal from a short brief.",
    category: "ai",
    inputType: "text-prompt",
    acceptedFileTypes: [],
    maxFiles: 0,
    requiresAiKey: true,
    endpoint: "/ai/proposal-writer",
    icon: "pen-line",
  },
];

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(category: ToolDefinition["category"]): ToolDefinition[] {
  return TOOLS.filter((tool) => tool.category === category);
}
